# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-14 21:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0003_author_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='author',
            field=models.ManyToManyField(related_name='book', to='books_authors_app.Author'),
        ),
    ]
